# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stower < Formula
  desc "Terminal UI for managing a dotfiles repository with GNU Stow"
  homepage "https://github.com/horbo/stower"
  version "0.5.1"
  license "MIT"

  depends_on "stow"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/horbo/stower/releases/download/v0.5.1/stower_0.5.1_darwin_amd64.tar.gz"
      sha256 "5b5d983a519a65a6aad0dacb2c230900feff6c7ef9b85f54019dfb0f765089ba"

      define_method(:install) do
        bin.install "stower"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/horbo/stower/releases/download/v0.5.1/stower_0.5.1_darwin_arm64.tar.gz"
      sha256 "5a80a3668049a41bd5591a8ec3773dc971a1d329cd2921a83fd5826a40baee18"

      define_method(:install) do
        bin.install "stower"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/horbo/stower/releases/download/v0.5.1/stower_0.5.1_linux_amd64.tar.gz"
      sha256 "6a576d5e3d9eaf2d57bf5a1750914e9a9062b00e743c45a1b3cce1e97c2b0f85"
      define_method(:install) do
        bin.install "stower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/horbo/stower/releases/download/v0.5.1/stower_0.5.1_linux_arm64.tar.gz"
      sha256 "eb735437e315d538fb129d2292d142acfb5339d2348fa2194f639aa54ef82c9c"
      define_method(:install) do
        bin.install "stower"
      end
    end
  end

  def caveats
    <<~EOS
      stower needs GNU Stow 2.4 or newer at runtime; it is installed as a dependency.
      git is optional: without it stower runs, only the commit popup and the dirty
      markers are unavailable.
    EOS
  end

  test do
    assert_match "stower #{version}", shell_output("#{bin}/stower --version")
  end
end
