# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stower < Formula
  desc "Terminal UI for managing a dotfiles repository with GNU Stow"
  homepage "https://github.com/horbo/stower"
  version "0.4.0"
  license "MIT"

  depends_on "stow"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/horbo/stower/releases/download/v0.4.0/stower_0.4.0_darwin_amd64.tar.gz"
      sha256 "58864472cdb3b4a9c21358bfe11d7f92680f5bc1091c980dda4f154cd7657ad0"

      define_method(:install) do
        bin.install "stower"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/horbo/stower/releases/download/v0.4.0/stower_0.4.0_darwin_arm64.tar.gz"
      sha256 "d2fedc5003e2e8e04fa1d62caac575c631e358f8eb132d7504d9dd6a6c6b0d3f"

      define_method(:install) do
        bin.install "stower"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/horbo/stower/releases/download/v0.4.0/stower_0.4.0_linux_amd64.tar.gz"
      sha256 "553e6cfe512c1f71861a32899c41b5fa0cdb8a754d49e7759c19ba4b27b34ab0"
      define_method(:install) do
        bin.install "stower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/horbo/stower/releases/download/v0.4.0/stower_0.4.0_linux_arm64.tar.gz"
      sha256 "54ab0c6382b44b129f1e1cd6509fbe1fb0f2f5ed7f496e5fd93da6677a434b51"
      define_method(:install) do
        bin.install "stower"
      end
    end
  end

  def caveats
    <<~EOS
      stower needs GNU Stow 2.4 or newer at runtime; it is installed as a dependency.
      git is optional: without it stower runs, only the commit popup and the dirty
      markers are unavailable.
    EOS
  end

  test do
    assert_match "stower #{version}", shell_output("#{bin}/stower --version")
  end
end
