# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stower < Formula
  desc "Terminal UI for managing a dotfiles repository with GNU Stow"
  homepage "https://github.com/horbo/stower"
  version "0.5.0"
  license "MIT"

  depends_on "stow"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/horbo/stower/releases/download/v0.5.0/stower_0.5.0_darwin_amd64.tar.gz"
      sha256 "8558d2631dcb61ac08afe6f9def8f691e4a85c27538761ad31609c1059eca688"

      define_method(:install) do
        bin.install "stower"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/horbo/stower/releases/download/v0.5.0/stower_0.5.0_darwin_arm64.tar.gz"
      sha256 "575090309d55d7af77e7cf0651ee9200f2adc46070465db322fd9173bae2d067"

      define_method(:install) do
        bin.install "stower"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/horbo/stower/releases/download/v0.5.0/stower_0.5.0_linux_amd64.tar.gz"
      sha256 "7a0f5df873c6e39c256a8bac01126ce7c31fb1a8edd7eb674ae17650a44210c4"
      define_method(:install) do
        bin.install "stower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/horbo/stower/releases/download/v0.5.0/stower_0.5.0_linux_arm64.tar.gz"
      sha256 "83d4f0c76c3b0b16661ca7a11cdfaf5d6d061eea1a624ff441ef289458f2ceeb"
      define_method(:install) do
        bin.install "stower"
      end
    end
  end

  def caveats
    <<~EOS
      stower needs GNU Stow 2.4 or newer at runtime; it is installed as a dependency.
      git is optional: without it stower runs, only the commit popup and the dirty
      markers are unavailable.
    EOS
  end

  test do
    assert_match "stower #{version}", shell_output("#{bin}/stower --version")
  end
end
